channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - absl-py=0.9.0
  - astor=0.8.1
  - blas=1.0
  - bz2file=0.98
  - c-ares=1.15.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.12.3
  - cloudpickle=0.8.1
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask-core=1.2.1
  - dbus=1.13.6
  - decorator=4.4.0
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.4.0
  - glib=2.56.2
  - grpcio=1.27.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - imageio=2.5.0
  - intel-openmp=2019.3
  - joblib=0.14.1
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - libcurl=7.71.1
  - libedit=3.1.20181209
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libprotobuf=3.7.1
  - libssh2=1.9.0
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=2.6.11
  - matplotlib=3.0.3
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=4.0.2
  - ncurses=6.1
  - networkx=2.3
  - nibabel=2.4.0
  - ninja=1.9.0
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - openssl=1.1.1g
  - pcre=8.43
  - pillow=6.0.0
  - pip=19.1.1
  - protobuf=3.7.1
  - pycparser=2.19
  - pydicom=1.2.2
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.8.0
  - python_abi=3.6
  - pytorch=1.2.0
  - pytz=2019.1
  - pywavelets=1.0.3
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.15.0
  - scikit-learn=0.21.1
  - scipy=1.2.1
  - setuptools=41.0.1
  - sip=4.19.13
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.13.1
  - tensorboardx=1.6
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - tk=8.6.8
  - toolz=0.9.0
  - torchvision=0.4.0
  - tornado=6.0.2
  - tqdm=4.31.1
  - werkzeug=0.15.2
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
